### ISSUE TITLE
when release the paper and code?

### ISSUE THREAD

**Issue by cnnAndBn** [vinthony/video-retalking#1]

**Comment by aishoot** [comment]
+1 request

**Comment by AdamBear** [comment]
+1 request

**Comment by skunkwerk** [comment]
+1

**Comment by tralala87** [comment]
Bump

**Comment by beyondchenlin** [comment]
期待ing

**Comment by lgzlIlIlI** [comment]
+1

**Comment by tommy19970714** [comment]
+1

**Comment by jackiezhang11** [comment]
+1

**Comment by seshubonam** [comment]
hey awesome work, was searching all day for audio to talking head for an mvp for ai tutor. while I'm in anticipation for this code, will checkout the Winfredy/SadTalker

**Comment by vinthony** [comment]
> hey awesome work, was searching all day for audio to talking head for an mvp for ai tutor. while I'm in anticipation for this code, will checkout the Winfredy/SadTalker

Thanks a lot, have fun!

**Comment by vinthony** [comment]
Thanks for the attentions. The inference code is released,

**Comment by RijulGupta-DM** [comment]
Hey @vinthony - are you all planning on releasing the training code as well? Really great work btw, the model architecture seems truly innovative.

**Comment by aishoot** [comment]
Nice work!

**Comment by seshubonam** [comment]
> Thanks for your attention. The inference code is released.

thanks for your contribution, is it suitable for real time talking head use case, like a video call with avatar? if not what area do you think needs improvement. we can improve and publish if possible
