### ISSUE TITLE
Odd GPEN Error - 'mask_sharp' referenced before assignment

### ISSUE THREAD

**Issue by indianajson** [vinthony/video-retalking#14]
When running inference.py the following error occurs when Step 5 begins

```Traceback (most recent call last):
  File "/inference.py", line 342, in <module>
    main()
  File "/inference.py", line 198, in main
    pred, _, _ = enhancer.process(img, img, face_enhance=True, possion_blending=False)
  File "/third_part/GPEN/gpen_face_enhancer.py", line 116, in process
    mask_sharp = cv2.GaussianBlur(mask_sharp, (0,0), sigmaX=1, sigmaY=1, borderType = cv2.BORDER_DEFAULT)
UnboundLocalError: local variable 'mask_sharp' referenced before assignment
```

What's likely the cause?

**Comment by kunncheng** [comment]
Sorry for the confusing error.
The reason seems to be that one frame in the video fails to detect a face. 
The GPEN detection code is [here.](https://github.com/vinthony/video-retalking/blob/f0c8767dcee67242bf4071f4eee200341e3b2bc2/third_part/GPEN/gpen_face_enhancer.py#L58)

**Comment by indianajson** [comment]
Thanks for getting back to me, I bypassed that bit of code but ran into other errors too. Eventually, I got an error telling me "face wasn't detected error", though I wasn't sure that is what was causing the other issues. I'm glad you let me know that's why all of the issues along the way. 

In situations like this, what's the best course of action? A different source video?

**Comment by kunncheng** [comment]
First you should check if there are any frames in your input video that don't have faces. You should cut out these clips.

In some cases, even though the input video contains full faces, the pre-trained detector still fails to detect them. 
In my experience, when the face resolution is too large or the face area proportion is too large, it may not be detected. This may be related to the face detector's training set.

**Comment by indianajson** [comment]
The source definitely has a face in every frame, but I think it may be face area proportion. I cropped the video quite a bit for my test and I'll bet that's why it's having trouble. 

Thanks so much for your help and fast response. This project is super exciting and I'm anticipating being blown away by my own results... as soon as I get an actual render. 😅

**Comment by PanJinquan** [comment]
fix this bug:
 `mask_sharp = np.zeros((height, width), dtype=np.float32)`

**Comment by blackjxxx** [comment]
> fix this bug: `mask_sharp = np.zeros((height, width), dtype=np.float32)`



> fix this bug: `mask_sharp = np.zeros((height, width), dtype=np.float32)`

Where to write this line of code

**Comment by Jeriousman** [comment]
@PanJinquan Can you specify where to insert that piece of code?

**Comment by caidewu** [comment]
@Jeriousman 
![微信图片_20231029091000](https://github.com/OpenTalker/video-retalking/assets/7226242/724a4f32-a0bc-4b7a-8e2a-cc46941023b8)

**Comment by Someonetoldme584** [comment]
I cant see the temps ?

**Comment by Fillllllllllll** [comment]
> @Jeriousman ![微信图片_20231029091000](https://private-user-images.githubusercontent.com/7226242/278845902-724a4f32-a0bc-4b7a-8e2a-cc46941023b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxOTMwNDQsIm5iZiI6MTcwMzE5Mjc0NCwicGF0aCI6Ii83MjI2MjQyLzI3ODg0NTkwMi03MjRhNGYzMi1hMGJjLTRiN2EtOGUyYS1jYzQ2OTQxMDIzYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMjEwNTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzZmOTFjZTAzY2RkOTJlYWRjNmVjZmZiMWZhOGM5NDUyMjM0ZTdkZWI0NDJmNjBjNjUwM2VjMzcxYWFmZDM0ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.O3msYXw7RY0bA0hRxwzLQxrz_-il0LLNs1Mdu5hKETs)

Hi! If i'm using colab version - where should i put this?

**Comment by arielweinberger** [comment]
@Fillllllllllll 
https://github.com/OpenTalker/video-retalking/blob/main/third_part/GPEN/gpen_face_enhancer.py
