### ISSUE TITLE
ValueError: cannot reshape array of size

### ISSUE THREAD

**Issue by zhangziliang04** [vinthony/video-retalking#18]
错误信息提示：
[Step 1] Using saved landmarks.
Traceback (most recent call last):
  File "inference.py", line 364, in <module>
    main()
  File "inference.py", line 88, in main
    lm = lm.reshape([len(full_frames), -1, 2])
ValueError: cannot reshape array of size 206040 into shape (6577,newaxis,2)
输入原始视频尺寸：
<img width="298" alt="image" src="https://user-images.githubusercontent.com/646709/228125397-01c9ec2c-555b-474e-a3e6-5bfda5150ad3.png">

不知道具体什么原因？对于的尺寸有具体要求吗？还是文件大小导致的？

**Comment by kunncheng** [comment]
是否测试了两个相同名称的视频？

`inference.py`会自动保存一些所需要的中间数据以减少下次推理的时间。这个问题可能是加载预处理好的数据与输入视频不匹配导致的。

你可以尝试删除`./temp`文件夹，或在推理的时候增加一个参数`--re_preprocess`

**Comment by zhangziliang04** [comment]
确认，增加--re_preprocess，可以解决问题。

**Comment by zhangziliang04** [comment]
确认，增加--re_preprocess，可以解决问题。
