### ISSUE TITLE
UnboundLocalError: local variable 'keypoints' referenced before assignment

### ISSUE THREAD

**Issue by onatkaya** [vinthony/video-retalking#182]
Hello everyone,

Has anyone faced this error during **_Step 1_**? 

![image](https://github.com/OpenTalker/video-retalking/assets/36605412/0f34386e-6549-496b-9916-e3203330b3b2)

Any help would be appreciated :)

**Comment by vettorazi** [comment]
I'm having this error. how did you solve it?
