### ISSUE TITLE
reshape error

### ISSUE THREAD

**Issue by zwz27837644** [vinthony/video-retalking#199]
demo video is ok~ my video is error
File "inference.py", line 88, in main
    lm = lm.reshape([len(full_frames), -1, 2])
 ValueError: cannot reshape array of size 27064 into shape (1290,newaxis,2)

**Comment by ZhuWenxuan123code** [comment]
I have the the problem

**Comment by ZhuWenxuan123code** [comment]
maybe the size of the video is too big

**Comment by zwz27837644** [comment]
Yes, I'll just segment the video. Thank you~
&nbsp;


Raining
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhuwen ***@***.***&gt;; 
发送时间: 2024年1月23日(星期二) 凌晨0:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [OpenTalker/video-retalking] reshape error (Issue #199)





 
maybe the size of the video is too big

**Comment by zwz27837644** [comment]
use segment, the video is too big!
&nbsp;


Raining
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhuwen ***@***.***&gt;; 
发送时间: 2024年1月23日(星期二) 凌晨0:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [OpenTalker/video-retalking] reshape error (Issue #199)





 
I have the the problem
